use_frameworks!

platform :ios, '8.0'

target 'pxsdk-lib-ios_Example' do
  pod 'pxsdk-lib-ios', :path => '../'

  target 'pxsdk-lib-ios_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
  end
end
